language: node_js
node_js:
  - "7"
 cache:
  directories:
  - node_modules
install: true
env:
  global:
   - secure: g4rrJfZNTLMNXymTj3fFDqFahi6gqTHST
  matrix:
    - TEST_SUITE=installs
matrix:
  include:
    - node_js: 0.10
      env: TEST_SUITE=simple